# -*- coding: utf-8 -*-
"""15F__45_seconds.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m3-_gkVfdeauCVfkJC2gzRC9IeN-uaH8
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import GroupShuffleSplit
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    confusion_matrix, ConfusionMatrixDisplay
)

# =====================================================
# 1. Load dataset
# =====================================================
df = pd.read_csv("/content/45_seconds_15F.csv")
print("Dataset shape:", df.shape)

# =====================================================
# 2. Feature list
# =====================================================
features = [
    "total_runtime_ns", "avg_runtime_ns", "runtime_var_ns",
    "total_wait_ns", "avg_wait_ns", "wait_var_ns",
    "wakeup_count", "switch_count",
    "runtime_per_switch", "wakeup_ratio",
    "wait_runtime_ratio", "cpu_util",
    "switch_rate", "wakeup_rate",
    "fairness_pressure"
]

# =====================================================
# 3. TWO-SIDED LABELING (UNCHANGED)
# =====================================================
rt_hi = df["total_runtime_ns"].quantile(0.70)
rt_lo = df["total_runtime_ns"].quantile(0.30)

wu_hi = df["wakeup_count"].quantile(0.70)
wu_lo = df["wakeup_count"].quantile(0.30)

labels = np.full(len(df), -1)

labels[
    (df["total_runtime_ns"] >= rt_hi) &
    (df["wakeup_count"] <= wu_lo)
] = 1

labels[
    (df["total_runtime_ns"] <= rt_lo) &
    (df["wakeup_count"] >= wu_hi)
] = 0

df["label"] = labels
df = df[df["label"] != -1]

print("\nLabel distribution:")
print(df["label"].value_counts())

# =====================================================
# 4. Prepare X and y
# =====================================================
X = df[features]
y = df["label"]

# =====================================================
# 5. Group-based split
# =====================================================
gss = GroupShuffleSplit(test_size=0.30, random_state=42)
train_idx, test_idx = next(gss.split(X, y, groups=df["pid"]))

X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

# =====================================================
# 6. Random Forest (FIXED)
# =====================================================
model = RandomForestClassifier(
    n_estimators=400,
    max_depth=14,
    min_samples_leaf=5,
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

# =====================================================
# 7. DATA-DRIVEN THRESHOLD (CRITICAL FIX)
# =====================================================
y_prob = model.predict_proba(X_test)[:, 1]

# Threshold = median probability (guarantees split)
threshold = np.median(y_prob)
print("Decision threshold:", round(threshold, 3))

y_pred = (y_prob >= threshold).astype(int)

# =====================================================
# 8. Metrics
# =====================================================
acc  = accuracy_score(y_test, y_pred)
prec = precision_score(y_test, y_pred, zero_division=0)
rec  = recall_score(y_test, y_pred, zero_division=0)
f1   = f1_score(y_test, y_pred, zero_division=0)

print("\nFINAL PERFORMANCE:")
print(f"Accuracy : {acc:.3f}")
print(f"Precision: {prec:.3f}")
print(f"Recall   : {rec:.3f}")
print(f"F1-score : {f1:.3f}")

# =====================================================
# 9. Confusion Matrix
# =====================================================
cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=["IO-bound", "CPU-bound"]
)
disp.plot()
plt.title("Confusion Matrix – Fixed (No All-Ones)")
plt.show()

# =====================================================
# 10. Metric Bar Chart
# =====================================================
plt.figure()
plt.bar(
    ["Accuracy", "Precision", "Recall", "F1-score"],
    [acc, prec, rec, f1]
)
plt.ylim(0, 1)
plt.ylabel("Score")
plt.title("Random Forest Performance – Fixed")
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import GroupShuffleSplit
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    confusion_matrix, ConfusionMatrixDisplay
)

# =====================================================
# 1. Load dataset
# =====================================================
df = pd.read_csv("/content/45_seconds_15F.csv")

print("Dataset shape:", df.shape)

# =====================================================
# 2. Feature list (15 scheduler features)
# =====================================================
features = [
    "total_runtime_ns", "avg_runtime_ns", "runtime_var_ns",
    "total_wait_ns", "avg_wait_ns", "wait_var_ns",
    "wakeup_count", "switch_count",
    "runtime_per_switch", "wakeup_ratio",
    "wait_runtime_ratio", "cpu_util",
    "switch_rate", "wakeup_rate",
    "fairness_pressure"
]

# =====================================================
# 3. TWO-SIDED scheduler-based labeling (SAME AS RF)
# =====================================================
rt_hi = df["total_runtime_ns"].quantile(0.75)
rt_lo = df["total_runtime_ns"].quantile(0.25)

wu_hi = df["wakeup_count"].quantile(0.75)
wu_lo = df["wakeup_count"].quantile(0.25)

labels = np.full(len(df), -1)

# CPU-bound
labels[
    (df["total_runtime_ns"] >= rt_hi) &
    (df["wakeup_count"] <= wu_lo)
] = 1

# IO-bound
labels[
    (df["total_runtime_ns"] <= rt_lo) &
    (df["wakeup_count"] >= wu_hi)
] = 0

df["label"] = labels

# Remove ambiguous windows
df = df[df["label"] != -1]

print("\nLabel distribution:")
print(df["label"].value_counts())

# =====================================================
# 4. Prepare X and y
# =====================================================
X = df[features]
y = df["label"]

# =====================================================
# 5. Group-based train/test split (NO PID LEAKAGE)
# =====================================================
gss = GroupShuffleSplit(test_size=0.30, random_state=42)
train_idx, test_idx = next(gss.split(X, y, groups=df["pid"]))

X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

# =====================================================
# 6. Feature scaling (MANDATORY for KNN)
# =====================================================
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# =====================================================
# 7. KNN model (scheduler-friendly)
# =====================================================
knn = KNeighborsClassifier(
    n_neighbors=7,       # odd to avoid ties
    weights="distance",  # closer neighbors matter more
    metric="minkowski"   # Euclidean
)

knn.fit(X_train_scaled, y_train)

# =====================================================
# 8. Predictions
# =====================================================
y_pred = knn.predict(X_test_scaled)

# =====================================================
# 9. Metrics
# =====================================================
acc  = accuracy_score(y_test, y_pred)
prec = precision_score(y_test, y_pred, zero_division=0)
rec  = recall_score(y_test, y_pred, zero_division=0)
f1   = f1_score(y_test, y_pred, zero_division=0)

print("\nKNN Performance:")
print(f"Accuracy : {acc:.3f}")
print(f"Precision: {prec:.3f}")
print(f"Recall   : {rec:.3f}")
print(f"F1-score : {f1:.3f}")

# =====================================================
# 10. Confusion Matrix
# =====================================================
cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=["IO-bound", "CPU-bound"]
)
disp.plot()
plt.title("Confusion Matrix – KNN Smart Scheduler")
plt.show()

# =====================================================
# 11. Metric comparison bar chart
# =====================================================
plt.figure()
plt.bar(
    ["Accuracy", "Precision", "Recall", "F1-score"],
    [acc, prec, rec, f1]
)
plt.ylim(0, 1)
plt.ylabel("Score")
plt.title("KNN Performance – Smart Scheduler")
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import GroupShuffleSplit
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    confusion_matrix, ConfusionMatrixDisplay
)

# =====================================================
# 1. Load dataset
# =====================================================
df = pd.read_csv("/content/45_seconds_15F.csv")
print("Dataset shape:", df.shape)

# =====================================================
# 2. Feature list (15 scheduler features)
# =====================================================
features = [
    "total_runtime_ns", "avg_runtime_ns", "runtime_var_ns",
    "total_wait_ns", "avg_wait_ns", "wait_var_ns",
    "wakeup_count", "switch_count",
    "runtime_per_switch", "wakeup_ratio",
    "wait_runtime_ratio", "cpu_util",
    "switch_rate", "wakeup_rate",
    "fairness_pressure"
]

# =====================================================
# 3. TWO-SIDED scheduler-based labeling (same as RF/KNN)
# =====================================================
rt_hi = df["total_runtime_ns"].quantile(0.75)
rt_lo = df["total_runtime_ns"].quantile(0.25)

wu_hi = df["wakeup_count"].quantile(0.75)
wu_lo = df["wakeup_count"].quantile(0.25)

labels = np.full(len(df), -1)

# CPU-bound
labels[
    (df["total_runtime_ns"] >= rt_hi) &
    (df["wakeup_count"] <= wu_lo)
] = 1

# IO-bound
labels[
    (df["total_runtime_ns"] <= rt_lo) &
    (df["wakeup_count"] >= wu_hi)
] = 0

df["label"] = labels

# Remove ambiguous windows
df = df[df["label"] != -1]

print("\nLabel distribution:")
print(df["label"].value_counts())

# =====================================================
# 4. Prepare X and y
# =====================================================
X = df[features]
y = df["label"]

# =====================================================
# 5. Group-based train/test split (NO PID LEAKAGE)
# =====================================================
gss = GroupShuffleSplit(test_size=0.30, random_state=42)
train_idx, test_idx = next(gss.split(X, y, groups=df["pid"]))

X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

# =====================================================
# 6. Gradient Boosting model (scheduler-friendly)
# =====================================================
gb = GradientBoostingClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=3,
    subsample=0.8,
    random_state=42
)

gb.fit(X_train, y_train)

# =====================================================
# 7. Predictions
# =====================================================
y_pred = gb.predict(X_test)

# =====================================================
# 8. Metrics
# =====================================================
acc  = accuracy_score(y_test, y_pred)
prec = precision_score(y_test, y_pred, zero_division=0)
rec  = recall_score(y_test, y_pred, zero_division=0)
f1   = f1_score(y_test, y_pred, zero_division=0)

print("\nGradient Boosting Performance:")
print(f"Accuracy : {acc:.3f}")
print(f"Precision: {prec:.3f}")
print(f"Recall   : {rec:.3f}")
print(f"F1-score : {f1:.3f}")

# =====================================================
# 9. Confusion Matrix
# =====================================================
cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=["IO-bound", "CPU-bound"]
)
disp.plot()
plt.title("Confusion Matrix – Gradient Boosting Smart Scheduler")
plt.show()

# =====================================================
# 10. Metric comparison bar chart
# =====================================================
plt.figure()
plt.bar(
    ["Accuracy", "Precision", "Recall", "F1-score"],
    [acc, prec, rec, f1]
)
plt.ylim(0, 1)
plt.ylabel("Score")
plt.title("Gradient Boosting Performance – Smart Scheduler")
plt.show()

# =====================================================
# 11. Feature importance
# =====================================================
importances = gb.feature_importances_
order = np.argsort(importances)[::-1]

plt.figure(figsize=(10, 5))
plt.bar(
    [features[i] for i in order],
    importances[order]
)
plt.xticks(rotation=45, ha="right")
plt.title("Feature Importance – Gradient Boosting")
plt.tight_layout()
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import GroupShuffleSplit
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    confusion_matrix, ConfusionMatrixDisplay
)

# =====================================================
# 1. Load dataset
# =====================================================
df = pd.read_csv("/content/sched_all_features.csv")
print("Dataset shape:", df.shape)

# =====================================================
# 2. Feature list (15 scheduler features)
# =====================================================
features = [
    "total_runtime_ns", "avg_runtime_ns", "runtime_var_ns",
    "total_wait_ns", "avg_wait_ns", "wait_var_ns",
    "wakeup_count", "switch_count",
    "runtime_per_switch", "wakeup_ratio",
    "wait_runtime_ratio", "cpu_util",
    "switch_rate", "wakeup_rate",
    "fairness_pressure"
]

# =====================================================
# 3. TWO-SIDED scheduler-based labeling
# =====================================================
rt_hi = df["total_runtime_ns"].quantile(0.75)
rt_lo = df["total_runtime_ns"].quantile(0.25)

wu_hi = df["wakeup_count"].quantile(0.75)
wu_lo = df["wakeup_count"].quantile(0.25)

labels = np.full(len(df), -1)

# CPU-bound
labels[
    (df["total_runtime_ns"] >= rt_hi) &
    (df["wakeup_count"] <= wu_lo)
] = 1

# IO-bound
labels[
    (df["total_runtime_ns"] <= rt_lo) &
    (df["wakeup_count"] >= wu_hi)
] = 0

df["label"] = labels

# Remove ambiguous windows
df = df[df["label"] != -1]

print("\nLabel distribution:")
print(df["label"].value_counts())

# =====================================================
# 4. Prepare X and y
# =====================================================
X = df[features]
y = df["label"]

# =====================================================
# 5. Group-based train/test split (NO PID LEAKAGE)
# =====================================================
gss = GroupShuffleSplit(test_size=0.30, random_state=42)
train_idx, test_idx = next(gss.split(X, y, groups=df["pid"]))

X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

# =====================================================
# 6. Feature scaling (MANDATORY for linear models)
# =====================================================
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# =====================================================
# 7. Linear Regression model
# =====================================================
lr = LinearRegression()
lr.fit(X_train_scaled, y_train)

# =====================================================
# 8. Predictions (continuous → binary)
# =====================================================
y_score = lr.predict(X_test_scaled)

# Threshold at 0.5 for classification
y_pred = (y_score >= 0.5).astype(int)

# =====================================================
# 9. Metrics
# =====================================================
acc  = accuracy_score(y_test, y_pred)
prec = precision_score(y_test, y_pred, zero_division=0)
rec  = recall_score(y_test, y_pred, zero_division=0)
f1   = f1_score(y_test, y_pred, zero_division=0)

print("\nLinear Regression Performance:")
print(f"Accuracy : {acc:.3f}")
print(f"Precision: {prec:.3f}")
print(f"Recall   : {rec:.3f}")
print(f"F1-score : {f1:.3f}")

# =====================================================
# 10. Confusion Matrix
# =====================================================
cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=["IO-bound", "CPU-bound"]
)
disp.plot()
plt.title("Confusion Matrix – Linear Regression Smart Scheduler")
plt.show()

# =====================================================
# 11. Metric comparison bar chart
# =====================================================
plt.figure()
plt.bar(
    ["Accuracy", "Precision", "Recall", "F1-score"],
    [acc, prec, rec, f1]
)
plt.ylim(0, 1)
plt.ylabel("Score")
plt.title("Linear Regression Performance – Smart Scheduler")
plt.show()

# =====================================================
# 12. Coefficient importance (interpretability)
# =====================================================
coef = lr.coef_
order = np.argsort(np.abs(coef))[::-1]

plt.figure(figsize=(10, 5))
plt.bar(
    [features[i] for i in order],
    np.abs(coef[order])
)
plt.xticks(rotation=45, ha="right")
plt.title("Feature Importance (|Coefficients|) – Linear Regression")
plt.tight_layout()
plt.show()

