# -*- coding: utf-8 -*-
"""5F_20sec_Random_forest_/KNN__/logisctic_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xpYR1Z6aXicNwUkFi8RjGXHo2nD5P_4i
"""

# ============================================================
# IMPROVED RANDOM FOREST – SMARTSCHEDULER (REALISTIC)
# Prevents 100% trivial accuracy
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedKFold, cross_val_predict
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, confusion_matrix, ConfusionMatrixDisplay
)

# ------------------------------------------------------------
# 1. LOAD DATA
# ------------------------------------------------------------
df = pd.read_csv('/content/sched_5F_20s.csv')

df['event_type'] = df['event'].map({
    'sched_runtime': 0,
    'sched_switch': 1,
    'sched_wakeup': 2,
    'sched_wakeup_new': 3,
    'sched_migrate': 4
}).fillna(0)

for col in ['timestamp', 'pid', 'cpu', 'value']:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df.fillna(0, inplace=True)

# ------------------------------------------------------------
# 2. FEATURE ENGINEERING
# ------------------------------------------------------------
features = pd.DataFrame({
    'pid': df['pid'],
    'cpu': df['cpu'],
    'runtime_ns': np.where(df['event_type'] == 0, df['value'], 0),
    'switch_count': np.where(df['event_type'] == 1, 1, 0),
    'wakeup_count': np.where(df['event_type'].isin([2, 3]), 1, 0),
    'migration_count': np.where(df['event_type'] == 4, 1, 0)
})

sched_df = features.groupby('pid', as_index=False).sum()

# ------------------------------------------------------------
# 3. SOFT LABELING (KEY IMPROVEMENT)
# ------------------------------------------------------------
# CPU intensity ratio
sched_df['cpu_ratio'] = (
    sched_df['runtime_ns'] /
    (sched_df['runtime_ns'] + sched_df['wakeup_count'] + 1)
)

# Add noise tolerance
low, high = sched_df['cpu_ratio'].quantile([0.4, 0.6])

sched_df['label'] = np.where(
    sched_df['cpu_ratio'] > high, 1,
    np.where(sched_df['cpu_ratio'] < low, 0, np.nan)
)

# Drop ambiguous tasks (realistic assumption)
sched_df = sched_df.dropna()

sched_df['label'] = sched_df['label'].astype(int)

print("Label distribution:")
print(sched_df['label'].value_counts())

# ------------------------------------------------------------
# 4. HARDER FEATURE SET (REMOVE runtime_ns)
# ------------------------------------------------------------
X = sched_df[
    ['cpu', 'switch_count', 'wakeup_count', 'migration_count']
]
y = sched_df['label']

# ------------------------------------------------------------
# 5. RANDOM FOREST + CROSS VALIDATION
# ------------------------------------------------------------
rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=10,
    min_samples_leaf=5,
    random_state=42,
    n_jobs=-1
)

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

y_pred = cross_val_predict(rf, X, y, cv=cv)

# ------------------------------------------------------------
# 6. METRICS
# ------------------------------------------------------------
accuracy  = accuracy_score(y, y_pred)
precision = precision_score(y, y_pred)
recall    = recall_score(y, y_pred)
f1        = f1_score(y, y_pred)

print("\n===== REALISTIC RANDOM FOREST RESULTS =====")
print(f"Accuracy  : {accuracy*100:.2f}%")
print(f"Precision : {precision*100:.2f}%")
print(f"Recall    : {recall*100:.2f}%")
print(f"F1 Score  : {f1*100:.2f}%")

# ------------------------------------------------------------
# 7. CONFUSION MATRIX
# ------------------------------------------------------------
cm = confusion_matrix(y, y_pred)

ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=["I/O-bound", "CPU-bound"]
).plot()

plt.title("Confusion Matrix – Improved Random Forest")
plt.show()

# ============================================================
# IMPROVED LOGISTIC REGRESSION – SMARTSCHEDULER (REALISTIC)
# Prevents 100% trivial accuracy
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold, cross_val_predict
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, confusion_matrix, ConfusionMatrixDisplay
)

# ------------------------------------------------------------
# 1. LOAD DATA
# ------------------------------------------------------------
df = pd.read_csv('/content/sched_5F_20s.csv')

df['event_type'] = df['event'].map({
    'sched_runtime': 0,
    'sched_switch': 1,
    'sched_wakeup': 2,
    'sched_wakeup_new': 3,
    'sched_migrate': 4
}).fillna(0)

for col in ['timestamp', 'pid', 'cpu', 'value']:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df.fillna(0, inplace=True)

# ------------------------------------------------------------
# 2. FEATURE ENGINEERING
# ------------------------------------------------------------
features = pd.DataFrame({
    'pid': df['pid'],
    'cpu': df['cpu'],
    'runtime_ns': np.where(df['event_type'] == 0, df['value'], 0),
    'switch_count': np.where(df['event_type'] == 1, 1, 0),
    'wakeup_count': np.where(df['event_type'].isin([2, 3]), 1, 0),
    'migration_count': np.where(df['event_type'] == 4, 1, 0)
})

sched_df = features.groupby('pid', as_index=False).sum()

# ------------------------------------------------------------
# 3. SOFT LABELING (KEY IMPROVEMENT)
# ------------------------------------------------------------
sched_df['cpu_ratio'] = (
    sched_df['runtime_ns'] /
    (sched_df['runtime_ns'] + sched_df['wakeup_count'] + 1)
)

low, high = sched_df['cpu_ratio'].quantile([0.4, 0.6])

sched_df['label'] = np.where(
    sched_df['cpu_ratio'] > high, 1,
    np.where(sched_df['cpu_ratio'] < low, 0, np.nan)
)

# Remove ambiguous tasks
sched_df = sched_df.dropna()
sched_df['label'] = sched_df['label'].astype(int)

print("Label distribution:")
print(sched_df['label'].value_counts())

# ------------------------------------------------------------
# 4. HARDER FEATURE SET (REMOVE runtime_ns)
# ------------------------------------------------------------
X = sched_df[
    ['cpu', 'switch_count', 'wakeup_count', 'migration_count']
]
y = sched_df['label']

# ------------------------------------------------------------
# 5. FEATURE SCALING (MANDATORY)
# ------------------------------------------------------------
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# ------------------------------------------------------------
# 6. LOGISTIC REGRESSION + CROSS VALIDATION
# ------------------------------------------------------------
logreg = LogisticRegression(
    max_iter=2000,
    solver='lbfgs',
    class_weight='balanced'   # IMPORTANT
)

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# Get probabilities using CV
y_prob = cross_val_predict(
    logreg,
    X_scaled,
    y,
    cv=cv,
    method='predict_proba'
)[:, 1]

# Scheduler-aware threshold (lower than 0.5)
threshold = 0.35
y_pred = (y_prob >= threshold).astype(int)

# ------------------------------------------------------------
# 7. METRICS
# ------------------------------------------------------------
accuracy  = accuracy_score(y, y_pred)
precision = precision_score(y, y_pred)
recall    = recall_score(y, y_pred)
f1        = f1_score(y, y_pred)

print("\n===== REALISTIC LOGISTIC REGRESSION RESULTS =====")
print(f"Accuracy  : {accuracy*100:.2f}%")
print(f"Precision : {precision*100:.2f}%")
print(f"Recall    : {recall*100:.2f}%")
print(f"F1 Score  : {f1*100:.2f}%")

# ------------------------------------------------------------
# 8. CONFUSION MATRIX
# ------------------------------------------------------------
cm = confusion_matrix(y, y_pred)

ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=["I/O-bound", "CPU-bound"]
).plot()

plt.title("Confusion Matrix – Improved Logistic Regression")
plt.show()

# ============================================================
# FINAL IMPROVED kNN – SMARTSCHEDULER
# Realistic performance (Recall NOT 100%)
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import StratifiedKFold, cross_val_predict
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, confusion_matrix, ConfusionMatrixDisplay
)

# ------------------------------------------------------------
# 1. LOAD DATA
# ------------------------------------------------------------
df = pd.read_csv('/content/sched_5F_20s.csv')

df['event_type'] = df['event'].map({
    'sched_runtime': 0,
    'sched_switch': 1,
    'sched_wakeup': 2,
    'sched_wakeup_new': 3,
    'sched_migrate': 4
}).fillna(0)

for col in ['timestamp', 'pid', 'cpu', 'value']:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df.fillna(0, inplace=True)

# ------------------------------------------------------------
# 2. FEATURE ENGINEERING
# ------------------------------------------------------------
features = pd.DataFrame({
    'pid': df['pid'],
    'cpu': df['cpu'],
    'runtime_ns': np.where(df['event_type'] == 0, df['value'], 0),
    'switch_count': np.where(df['event_type'] == 1, 1, 0),
    'wakeup_count': np.where(df['event_type'].isin([2, 3]), 1, 0),
    'migration_count': np.where(df['event_type'] == 4, 1, 0)
})

sched_df = features.groupby('pid', as_index=False).sum()

# ------------------------------------------------------------
# 3. SOFT LABELING (CPU INTENSITY)
# ------------------------------------------------------------
sched_df['cpu_ratio'] = (
    sched_df['runtime_ns'] /
    (sched_df['runtime_ns'] + sched_df['wakeup_count'] + 1)
)

low_q, high_q = sched_df['cpu_ratio'].quantile([0.4, 0.6])

sched_df['label'] = np.where(
    sched_df['cpu_ratio'] > high_q, 1,
    np.where(sched_df['cpu_ratio'] < low_q, 0, np.nan)
)

# Remove ambiguous tasks
sched_df = sched_df.dropna()
sched_df['label'] = sched_df['label'].astype(int)

print("Label distribution:")
print(sched_df['label'].value_counts())

# ------------------------------------------------------------
# 4. HARDER FEATURE SET (NO runtime_ns)
# ------------------------------------------------------------
X = sched_df[['cpu', 'switch_count', 'wakeup_count', 'migration_count']]
y = sched_df['label']

# ------------------------------------------------------------
# 5. FEATURE SCALING (MANDATORY FOR kNN)
# ------------------------------------------------------------
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# ------------------------------------------------------------
# 6. kNN (MORE CONSERVATIVE SETUP)
# ------------------------------------------------------------
knn = KNeighborsClassifier(
    n_neighbors=11,      # larger k → less aggressive
    weights='uniform',   # prevents overconfidence
    metric='minkowski'
)

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

y_pred = cross_val_predict(
    knn,
    X_scaled,
    y,
    cv=cv
)

# ------------------------------------------------------------
# 7. METRICS
# ------------------------------------------------------------
accuracy  = accuracy_score(y, y_pred)
precision = precision_score(y, y_pred)
recall    = recall_score(y, y_pred)
f1        = f1_score(y, y_pred)

print("\n===== FINAL kNN RESULTS =====")
print(f"Accuracy  : {accuracy*100:.2f}%")
print(f"Precision : {precision*100:.2f}%")
print(f"Recall    : {recall*100:.2f}%")
print(f"F1 Score  : {f1*100:.2f}%")

# ------------------------------------------------------------
# 8. CONFUSION MATRIX
# ------------------------------------------------------------
cm = confusion_matrix(y, y_pred)

ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=["I/O-bound", "CPU-bound"]
).plot()

plt.title("Confusion Matrix – Final kNN")
plt.show()