# -*- coding: utf-8 -*-
"""Randomforest_3F_5S.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DHn6tCM-91UA2_2fxJSOxCsLoQiZPLoQ
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score
)

# -------------------------------------------------
# Load dataset
# -------------------------------------------------
df = pd.read_csv("/sched_trace_3_features.csv")

# Encode categorical features
for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = pd.factorize(df[col])[0]

# -------------------------------------------------
# Create binary label (runtime-based)
# -------------------------------------------------
threshold = df.iloc[:, 4].median()
y = (df.iloc[:, 4] > threshold).astype(int)
X = df.iloc[:, :4]

print("Class distribution:\n", y.value_counts())

# -------------------------------------------------
# Train-test split
# -------------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# -------------------------------------------------
# Random Forest
# -------------------------------------------------
rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

# -------------------------------------------------
# Evaluation (ADDED METRICS)
# -------------------------------------------------
acc = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

print("\nModel Performance:")
print("Accuracy :", acc)
print("Precision:", precision)
print("Recall   :", recall)
print("F1 Score :", f1)
print("\nConfusion Matrix:\n", cm)

# =================================================
# 📊 GRAPH 1: Confusion Matrix
# =================================================
plt.figure()
plt.imshow(cm)
plt.title("Confusion Matrix - Random Forest")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.colorbar()

for i in range(cm.shape[0]):
    for j in range(cm.shape[1]):
        plt.text(j, i, cm[i, j], ha="center", va="center")

plt.tight_layout()
plt.show()

# =================================================
# 🌲 GRAPH 2: Feature Importance
# =================================================
importances = rf.feature_importances_
features = X.columns

plt.figure()
plt.bar(range(len(importances)), importances)
plt.xticks(range(len(importances)), features, rotation=45)
plt.ylabel("Importance Score")
plt.title("Feature Importance (Random Forest)")
plt.tight_layout()
plt.show()

from google.colab import drive
drive.mount('/content/drive')