# -*- coding: utf-8 -*-
"""15F_20secs_random forrest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nYR1K10K_9m-1AnOYF12Lsce_SI2_FIH
"""

# ==========================================================
# FIXED CPU vs IO Classification (NO ALL-ONES ISSUE)
# ==========================================================

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    confusion_matrix,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report
)

# ----------------------------------------------------------
# 1. Load dataset
# ----------------------------------------------------------
df = pd.read_csv("/content/sched_15_features.csv")

# ----------------------------------------------------------
# 2. SEMANTIC LABELING (FIXED)
#    Uses multiple scheduler signals instead of single ratio
# ----------------------------------------------------------
df["task_type"] = np.where(
    (df["cpu_util"] >= df["cpu_util"].quantile(0.6)) &              # high CPU usage
    (df["wait_runtime_ratio"] <= df["wait_runtime_ratio"].quantile(0.4)) &  # low waiting
    (df["wakeup_rate"] <= df["switch_rate"]),                       # compute-dominant
    1,   # CPU-bound
    0    # IO-bound
)

# ----------------------------------------------------------
# 3. Verify class balance (IMPORTANT)
# ----------------------------------------------------------
print("\nLabel distribution:")
print(df["task_type"].value_counts())

# ----------------------------------------------------------
# 4. Feature matrix and label
# ----------------------------------------------------------
X = df.drop(columns=["pid", "window", "task_type"])
y = df["task_type"]

# ----------------------------------------------------------
# 5. Train-test split
# ----------------------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# ----------------------------------------------------------
# 6. Train Random Forest
# ----------------------------------------------------------
rf = RandomForestClassifier(
    n_estimators=300,
    max_depth=12,
    min_samples_split=5,
    min_samples_leaf=2,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

# ----------------------------------------------------------
# 7. Prediction
# ----------------------------------------------------------
y_pred = rf.predict(X_test)

# ----------------------------------------------------------
# 8. Evaluation
# ----------------------------------------------------------
cm = confusion_matrix(y_test, y_pred, labels=[0, 1])

print("\n================ CONFUSION MATRIX ================")
print(cm)

print("\n================ METRICS ================")
print(f"Accuracy  : {accuracy_score(y_test, y_pred):.4f}")
print(f"Precision : {precision_score(y_test, y_pred, zero_division=0):.4f}")
print(f"Recall    : {recall_score(y_test, y_pred, zero_division=0):.4f}")
print(f"F1 Score  : {f1_score(y_test, y_pred, zero_division=0):.4f}")

print("\n================ CLASSIFICATION REPORT ================")
print(classification_report(
    y_test,
    y_pred,
    labels=[0, 1],
    target_names=["IO-bound", "CPU-bound"],
    zero_division=0
))

# ----------------------------------------------------------
# 9. Feature importance
# ----------------------------------------------------------
importance = pd.Series(
    rf.feature_importances_,
    index=X.columns
).sort_values(ascending=False)

print("\n================ FEATURE IMPORTANCE ================")
print(importance)

# ==========================================================
# CPU-bound vs IO-bound Classification (ALL-IN-ONE FINAL)
# ==========================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    confusion_matrix,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report
)

# ----------------------------------------------------------
# 1. Load dataset
# ----------------------------------------------------------
df = pd.read_csv("/content/sched_15_features.csv")

print("Dataset columns:")
print(df.columns.tolist())

# ----------------------------------------------------------
# 2. SEMANTIC LABELING (FIXES ALL-ONES ISSUE)
# ----------------------------------------------------------
df["task_type"] = np.where(
    (df["cpu_util"] >= df["cpu_util"].quantile(0.6)) &                # high CPU usage
    (df["wait_runtime_ratio"] <= df["wait_runtime_ratio"].quantile(0.4)) &  # low waiting
    (df["wakeup_rate"] <= df["switch_rate"]),                         # compute dominant
    1,   # CPU-bound
    0    # IO-bound
)

print("\nLabel distribution:")
print(df["task_type"].value_counts())

# ----------------------------------------------------------
# 3. Feature matrix and label
# ----------------------------------------------------------
X = df.drop(columns=["pid", "window", "task_type"])
y = df["task_type"]

# ----------------------------------------------------------
# 4. Train-test split
# ----------------------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# ----------------------------------------------------------
# 5. Train Random Forest
# ----------------------------------------------------------
rf = RandomForestClassifier(
    n_estimators=300,
    max_depth=12,
    min_samples_split=5,
    min_samples_leaf=2,
    n_jobs=-1,
    random_state=42
)

rf.fit(X_train, y_train)

# ----------------------------------------------------------
# 6. Prediction
# ----------------------------------------------------------
y_pred = rf.predict(X_test)

# ----------------------------------------------------------
# 7. Evaluation Metrics
# ----------------------------------------------------------
cm = confusion_matrix(y_test, y_pred, labels=[0, 1])

accuracy  = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, zero_division=0)
recall    = recall_score(y_test, y_pred, zero_division=0)
f1        = f1_score(y_test, y_pred, zero_division=0)

print("\n================ CONFUSION MATRIX ================")
print(cm)

print("\n================ METRICS ================")
print(f"Accuracy  : {accuracy:.4f}")
print(f"Precision : {precision:.4f}")
print(f"Recall    : {recall:.4f}")
print(f"F1 Score  : {f1:.4f}")

print("\n================ CLASSIFICATION REPORT ================")
print(classification_report(
    y_test,
    y_pred,
    labels=[0, 1],
    target_names=["IO-bound", "CPU-bound"],
    zero_division=0
))

# ----------------------------------------------------------
# 8. Confusion Matrix Graph
# ----------------------------------------------------------
labels = ["IO-bound", "CPU-bound"]

fig, ax = plt.subplots(figsize=(5, 4))
im = ax.imshow(cm)

for i in range(cm.shape[0]):
    for j in range(cm.shape[1]):
        ax.text(j, i, cm[i, j], ha="center", va="center")

ax.set_xticks(np.arange(len(labels)))
ax.set_yticks(np.arange(len(labels)))
ax.set_xticklabels(labels)
ax.set_yticklabels(labels)

ax.set_xlabel("Predicted Label")
ax.set_ylabel("True Label")
ax.set_title("Confusion Matrix: CPU-bound vs IO-bound")

plt.tight_layout()
plt.show()

# ----------------------------------------------------------
# 9. Feature Impor



# ==========================================================
# CPU-bound vs IO-bound Classification (GRADIENT BOOSTING)
# ==========================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import (
    confusion_matrix,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report
)

# ----------------------------------------------------------
# 1. Load dataset
# ----------------------------------------------------------
df = pd.read_csv("/content/sched_15_features.csv")

print("Dataset columns:")
print(df.columns.tolist())

# ----------------------------------------------------------
# 2. SEMANTIC LABELING (FIXES ALL-ONES ISSUE)
# ----------------------------------------------------------
df["task_type"] = np.where(
    (df["cpu_util"] >= df["cpu_util"].quantile(0.6)) &                 # high CPU usage
    (df["wait_runtime_ratio"] <= df["wait_runtime_ratio"].quantile(0.4)) &  # low waiting
    (df["wakeup_rate"] <= df["switch_rate"]),                          # compute-dominant
    1,   # CPU-bound
    0    # IO-bound
)

print("\nLabel distribution:")
print(df["task_type"].value_counts())

# ----------------------------------------------------------
# 3. Feature matrix and label
# ----------------------------------------------------------
X = df.drop(columns=["pid", "window", "task_type"])
y = df["task_type"]

# ----------------------------------------------------------
# 4. Train-test split
# ----------------------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# ----------------------------------------------------------
# 5. Train Gradient Boosting Classifier
# ----------------------------------------------------------
gb = GradientBoostingClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=3,
    random_state=42
)

gb.fit(X_train, y_train)

# ----------------------------------------------------------
# 6. Prediction
# ----------------------------------------------------------
y_pred = gb.predict(X_test)

# ----------------------------------------------------------
# 7. Evaluation Metrics
# ----------------------------------------------------------
cm = confusion_matrix(y_test, y_pred, labels=[0, 1])

accuracy  = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, zero_division=0)
recall    = recall_score(y_test, y_pred, zero_division=0)
f1        = f1_score(y_test, y_pred, zero_division=0)

print("\n================ CONFUSION MATRIX ================")
print(cm)

print("\n================ METRICS ================")
print(f"Accuracy  : {accuracy:.4f}")
print(f"Precision : {precision:.4f}")
print(f"Recall    : {recall:.4f}")
print(f"F1 Score  : {f1:.4f}")

print("\n================ CLASSIFICATION REPORT ================")
print(classification_report(
    y_test,
    y_pred,
    labels=[0, 1],
    target_names=["IO-bound", "CPU-bound"],
    zero_division=0
))

# ----------------------------------------------------------
# 8. Confusion Matrix Graph
# ----------------------------------------------------------
labels = ["IO-bound", "CPU-bound"]

fig, ax = plt.subplots(figsize=(5, 4))
ax.imshow(cm)

for i in range(cm.shape[0]):
    for j in range(cm.shape[1]):
        ax.text(j, i, cm[i, j], ha="center", va="center")

ax.set_xticks(np.arange(len(labels)))
ax.set_yticks(np.arange(len(labels)))
ax.set_xticklabels(labels)
ax.set_yticklabels(labels)

ax.set_xlabel("Predicted Label")
ax.set_ylabel("True Label")
ax.set_title("Confusion Matrix (Gradient Boosting)")

plt.tight_layout()
plt.show()

# ----------------------------------------------------------
# 9. Feature Importance (Gradient Boosting)
# ----------------------------------------------------------
importance = pd.Series(
    gb.feature_importances_,
    index=X.columns
).sort_values(ascending=False)

print("\n================ FEATURE IMPORTANCE ================")
print(importance)

# ----------------------------------------------------------
# END
# ----------------------------------------------------------

# ==========================================================
# CPU-bound vs IO-bound Classification (KNN)
# ==========================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    confusion_matrix,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report
)

# ----------------------------------------------------------
# 1. Load dataset
# ----------------------------------------------------------
df = pd.read_csv("/content/sched_15_features.csv")

print("Dataset columns:")
print(df.columns.tolist())

# ----------------------------------------------------------
# 2. SEMANTIC LABELING (FIXES ALL-ONES ISSUE)
# ----------------------------------------------------------
df["task_type"] = np.where(
    (df["cpu_util"] >= df["cpu_util"].quantile(0.6)) &                 # high CPU usage
    (df["wait_runtime_ratio"] <= df["wait_runtime_ratio"].quantile(0.4)) &  # low waiting
    (df["wakeup_rate"] <= df["switch_rate"]),                          # compute-dominant
    1,   # CPU-bound
    0    # IO-bound
)

print("\nLabel distribution:")
print(df["task_type"].value_counts())

# ----------------------------------------------------------
# 3. Feature matrix and label
# ----------------------------------------------------------
X = df.drop(columns=["pid", "window", "task_type"])
y = df["task_type"]

# ----------------------------------------------------------
# 4. Train-test split
# ----------------------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# ----------------------------------------------------------
# 5. Feature Scaling (CRITICAL FOR KNN)
# ----------------------------------------------------------
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

# ----------------------------------------------------------
# 6. Train KNN Classifier
# ----------------------------------------------------------
knn = KNeighborsClassifier(
    n_neighbors=7,
    weights="distance",
    metric="euclidean"
)

knn.fit(X_train_scaled, y_train)

# ----------------------------------------------------------
# 7. Prediction
# ----------------------------------------------------------
y_pred = knn.predict(X_test_scaled)

# ----------------------------------------------------------
# 8. Evaluation Metrics
# ----------------------------------------------------------
cm = confusion_matrix(y_test, y_pred, labels=[0, 1])

accuracy  = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, zero_division=0)
recall    = recall_score(y_test, y_pred, zero_division=0)
f1        = f1_score(y_test, y_pred, zero_division=0)

print("\n================ CONFUSION MATRIX ================")
print(cm)

print("\n================ METRICS ================")
print(f"Accuracy  : {accuracy:.4f}")
print(f"Precision : {precision:.4f}")
print(f"Recall    : {recall:.4f}")
print(f"F1 Score  : {f1:.4f}")

print("\n================ CLASSIFICATION REPORT ================")
print(classification_report(
    y_test,
    y_pred,
    labels=[0, 1],
    target_names=["IO-bound", "CPU-bound"],
    zero_division=0
))

# ----------------------------------------------------------
# 9. Confusion Matrix Graph
# ----------------------------------------------------------
labels = ["IO-bound", "CPU-bound"]

fig, ax = plt.subplots(figsize=(5, 4))
ax.imshow(cm)

for i in range(cm.shape[0]):
    for j in range(cm.shape[1]):
        ax.text(j, i, cm[i, j], ha="center", va="center")

ax.set_xticks(np.arange(len(labels)))
ax.set_yticks(np.arange(len(labels)))
ax.set_xticklabels(labels)
ax.set_yticklabels(labels)

ax.set_xlabel("Predicted Label")
ax.set_ylabel("True Label")
ax.set_title("Confusion Matrix (KNN)")

plt.tight_layout()
plt.show()

# ----------------------------------------------------------
# END
# ----------------------------------------------------------

# ==========================================================
# CPU-bound vs IO-bound Classification (XGBoost)
# ==========================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    confusion_matrix,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report
)

from xgboost import XGBClassifier

# ----------------------------------------------------------
# 1. Load dataset
# ----------------------------------------------------------
df = pd.read_csv("/content/sched_15_features.csv")

print("Dataset columns:")
print(df.columns.tolist())

# ----------------------------------------------------------
# 2. SEMANTIC LABELING (FIXES ALL-ONES ISSUE)
# ----------------------------------------------------------
df["task_type"] = np.where(
    (df["cpu_util"] >= df["cpu_util"].quantile(0.6)) &                 # high CPU usage
    (df["wait_runtime_ratio"] <= df["wait_runtime_ratio"].quantile(0.4)) &  # low waiting
    (df["wakeup_rate"] <= df["switch_rate"]),                          # compute-dominant
    1,   # CPU-bound
    0    # IO-bound
)

print("\nLabel distribution:")
print(df["task_type"].value_counts())

# ----------------------------------------------------------
# 3. Feature matrix and label
# ----------------------------------------------------------
X = df.drop(columns=["pid", "window", "task_type"])
y = df["task_type"]

# ----------------------------------------------------------
# 4. Train-test split
# ----------------------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# ----------------------------------------------------------
# 5. Train XGBoost Classifier
# ----------------------------------------------------------
xgb = XGBClassifier(
    n_estimators=300,
    max_depth=4,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="binary:logistic",
    eval_metric="logloss",
    random_state=42,
    n_jobs=-1
)

xgb.fit(X_train, y_train)

# ----------------------------------------------------------
# 6. Prediction
# ----------------------------------------------------------
y_pred = xgb.predict(X_test)

# ----------------------------------------------------------
# 7. Evaluation Metrics
# ----------------------------------------------------------
cm = confusion_matrix(y_test, y_pred, labels=[0, 1])

accuracy  = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, zero_division=0)
recall    = recall_score(y_test, y_pred, zero_division=0)
f1        = f1_score(y_test, y_pred, zero_division=0)

print("\n================ CONFUSION MATRIX ================")
print(cm)

print("\n================ METRICS ================")
print(f"Accuracy  : {accuracy:.4f}")
print(f"Precision : {precision:.4f}")
print(f"Recall    : {recall:.4f}")
print(f"F1 Score  : {f1:.4f}")

print("\n================ CLASSIFICATION REPORT ================")
print(classification_report(
    y_test,
    y_pred,
    labels=[0, 1],
    target_names=["IO-bound", "CPU-bound"],
    zero_division=0
))

# ----------------------------------------------------------
# 8. Confusion Matrix Graph
# ----------------------------------------------------------
labels = ["IO-bound", "CPU-bound"]

fig, ax = plt.subplots(figsize=(5, 4))
ax.imshow

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    confusion_matrix,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report
)

# ----------------------------------------------------------
# 1. Load dataset
# ----------------------------------------------------------
df = pd.read_csv("/content/sched_15_features.csv")

print("Dataset columns:")
print(df.columns.tolist())

# ----------------------------------------------------------
# 2. SEMANTIC LABELING (SAME AS RF)
# ----------------------------------------------------------
df["task_type"] = np.where(
    (df["cpu_util"] >= df["cpu_util"].quantile(0.6)) &
    (df["wait_runtime_ratio"] <= df["wait_runtime_ratio"].quantile(0.4)) &
    (df["wakeup_rate"] <= df["switch_rate"]),
    1,   # CPU-bound
    0    # IO-bound
)

print("\nLabel distribution:")
print(df["task_type"].value_counts())

# ----------------------------------------------------------
# 3. Feature matrix and label
# ----------------------------------------------------------
X = df.drop(columns=["pid", "window", "task_type"])
y = df["task_type"]

# ----------------------------------------------------------
# 4. Train-test split
# ----------------------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# ----------------------------------------------------------
# 5. Feature Scaling (MANDATORY for LR)
# ----------------------------------------------------------
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)

# ----------------------------------------------------------
# 6. Train Logistic Regression
# ----------------------------------------------------------
lr = LogisticRegression(
    max_iter=2000,
    solver="lbfgs",
    n_jobs=-1
)

lr.fit(X_train, y_train)

# ----------------------------------------------------------
# 7. Prediction
# ----------------------------------------------------------
y_pred = lr.predict(X_test)

# ----------------------------------------------------------
# 8. Evaluation Metrics
# ----------------------------------------------------------
cm = confusion_matrix(y_test, y_pred, labels=[0, 1])

accuracy  = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, zero_division=0)
recall    = recall_score(y_test, y_pred, zero_division=0)
f1        = f1_score(y_test, y_pred, zero_division=0)

print("\n================ CONFUSION MATRIX ================")
print(cm)

print("\n================ METRICS ================")
print(f"Accuracy  : {accuracy:.4f}")
print(f"Precision : {precision:.4f}")
print(f"Recall    : {recall:.4f}")
print(f"F1 Score  : {f1:.4f}")

print("\n================ CLASSIFICATION REPORT ================")
print(classification_report(
    y_test,
    y_pred,
    labels=[0, 1],
    target_names=["IO-bound", "CPU-bound"],
    zero_division=0
))

# ----------------------------------------------------------
# 9. Confusion Matrix Graph
# ----------------------------------------------------------
labels = ["IO-bound", "CPU-bound"]

fig, ax = plt.subplots(figsize=(5, 4))
im = ax.imshow(cm)

for i in range(cm.shape[0]):
    for j in range(cm.shape[1]):
        ax.text(j, i, cm[i, j], ha="center", va="center")

ax.set_xticks(np.arange(len(labels)))
ax.set_yticks(np.arange(len(labels)))
ax.set_xticklabels(labels)
ax.set_yticklabels(labels)

ax.set_xlabel("Predicted Label")
ax.set_ylabel("True Label")
ax.set_title("Confusion Matrix: CPU-bound vs IO-bound (Logistic Regression)")

plt.tight_layout()
plt.show()

# ----------------------------------------------------------
# 10. Metric Comparison Graph
# ----------------------------------------------------------
metrics = ["Accuracy", "Precision", "Recall", "F1 Score"]
values = [accuracy, precision, recall, f1]

plt.figure(figsize=(6, 4))
plt.bar(metrics, values)
plt.ylim(0, 1.05)
plt.ylabel("Score")
plt.title("Logistic Regression Performance")
plt.grid(axis="y", linestyle="--", alpha=0.7)
plt.show()