# -*- coding: utf-8 -*-
"""3F_20sec_RANDOM_FOREST_KNN__LOGISTIC _REGRESSION.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/196pObM2S3A7cf-CCasVc2xaWhOIrCoGP
"""

# ============================================================
# MODIFIED RANDOM FOREST – SMARTSCHEDULER (REALISTIC)
# Prevents 100% accuracy
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedKFold, cross_val_predict
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    ConfusionMatrixDisplay
)

# ------------------------------------------------------------
# 1. LOAD CSV
# ------------------------------------------------------------
df = pd.read_csv(
    '/content/sched_3F_20_sec.csv',
    header=None,
    names=['event', 'timestamp', 'pid', 'comm', 'cpu', 'value']
)

df['event_type'] = df['event'].map({
    'sched_runtime': 0,
    'sched_switch': 1,
    'sched_wakeup': 2
}).fillna(0)

for col in ['timestamp', 'pid', 'cpu', 'value']:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df.fillna(0, inplace=True)

# ------------------------------------------------------------
# 2. FEATURE ENGINEERING
# ------------------------------------------------------------
features = pd.DataFrame({
    'pid': df['pid'],
    'cpu': df['cpu'],
    'runtime_ns': np.where(df['event_type'] == 0, df['value'], 0),
    'switch_count': np.where(df['event_type'] == 1, 1, 0),
    'wakeup_count': np.where(df['event_type'] == 2, 1, 0),
})

sched_df = features.groupby('pid', as_index=False).sum()

# ------------------------------------------------------------
# 3. SOFT LABELING (KEY FIX)
# ------------------------------------------------------------
# CPU intensity score
sched_df['cpu_intensity'] = (
    sched_df['runtime_ns'] /
    (sched_df['runtime_ns'] + sched_df['wakeup_count'] + 1)
)

low_q, high_q = sched_df['cpu_intensity'].quantile([0.4, 0.6])

sched_df['label'] = np.where(
    sched_df['cpu_intensity'] > high_q, 1,
    np.where(sched_df['cpu_intensity'] < low_q, 0, np.nan)
)

# Remove ambiguous tasks
sched_df = sched_df.dropna()
sched_df['label'] = sched_df['label'].astype(int)

print("\nLabel distribution:")
print(sched_df['label'].value_counts())

# ------------------------------------------------------------
# 4. HARDER FEATURE SET (REMOVE runtime_ns)
# ------------------------------------------------------------
X = sched_df[['cpu', 'switch_count', 'wakeup_count']]
y = sched_df['label']

# ------------------------------------------------------------
# 5. RANDOM FOREST + CROSS VALIDATION
# ------------------------------------------------------------
rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=10,
    min_samples_leaf=5,
    random_state=42,
    n_jobs=-1
)

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

y_pred = cross_val_predict(rf, X, y, cv=cv)

# ------------------------------------------------------------
# 6. METRICS
# ------------------------------------------------------------
accuracy  = accuracy_score(y, y_pred)
precision = precision_score(y, y_pred)
recall    = recall_score(y, y_pred)
f1        = f1_score(y, y_pred)

print("\n===== REALISTIC RANDOM FOREST RESULTS =====")
print(f"Accuracy  : {accuracy*100:.2f}%")
print(f"Precision : {precision*100:.2f}%")
print(f"Recall    : {recall*100:.2f}%")
print(f"F1 Score  : {f1*100:.2f}%")

# ------------------------------------------------------------
# 7. CONFUSION MATRIX
# ------------------------------------------------------------
cm = confusion_matrix(y, y_pred)

ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=["I/O-bound", "CPU-bound"]
).plot()

plt.title("Confusion Matrix – Modified Random Forest")
plt.show()

# ============================================================
# FINAL kNN CODE – SMARTSCHEDULER
# CPU-bound vs I/O-bound (bpftrace CSV)
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    ConfusionMatrixDisplay
)

# ------------------------------------------------------------
# 1. LOAD CSV (bpftrace files have NO header)
# ------------------------------------------------------------
df = pd.read_csv(
    '/content/sched_3F_20_sec.csv',
    header=None,
    names=['event', 'timestamp', 'pid', 'comm', 'cpu', 'value']
)

print("Dataset loaded successfully")
print(df.head())

# ------------------------------------------------------------
# 2. DATA CLEANING
# ------------------------------------------------------------
df['event'] = df['event'].astype(str)

df['event_type'] = df['event'].map({
    'sched_runtime': 0,
    'sched_switch': 1,
    'sched_wakeup': 2
}).fillna(0)

for col in ['timestamp', 'pid', 'cpu', 'value']:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df.fillna(0, inplace=True)

# ------------------------------------------------------------
# 3. FEATURE ENGINEERING (NO LABEL LEAKAGE)
# ------------------------------------------------------------
features = pd.DataFrame()

features['pid'] = df['pid']
features['cpu'] = df['cpu']

features['runtime_ns'] = np.where(
    df['event_type'] == 0,
    df['value'],
    0
)

features['switch_count'] = np.where(
    df['event_type'] == 1,
    1,
    0
)

features['wakeup_count'] = np.where(
    df['event_type'] == 2,
    1,
    0
)

# ------------------------------------------------------------
# 4. AGGREGATE PER PID
# ------------------------------------------------------------
sched_df = features.groupby('pid', as_index=False).agg({
    'cpu': 'mean',
    'runtime_ns': 'sum',
    'switch_count': 'sum',
    'wakeup_count': 'sum'
})

print("\nAggregated scheduler features:")
print(sched_df.head())

# ------------------------------------------------------------
# 5. LABEL CREATION (CPU vs I/O) – SAFE
# ------------------------------------------------------------
runtime_thr = sched_df['runtime_ns'].median()
wakeup_thr  = sched_df['wakeup_count'].median()

sched_df['label'] = np.where(
    (sched_df['runtime_ns'] > runtime_thr) &
    (sched_df['wakeup_count'] <= wakeup_thr),
    1,   # CPU-bound
    0    # I/O-bound
)

print("\nLabel distribution (0=IO, 1=CPU):")
print(sched_df['label'].value_counts())

# ------------------------------------------------------------
# 6. TRAIN–TEST SPLIT
# ------------------------------------------------------------
X = sched_df[
    ['cpu', 'runtime_ns', 'switch_count', 'wakeup_count']
]
y = sched_df['label']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42,
    stratify=y
)

# ------------------------------------------------------------
# 7. FEATURE SCALING (MANDATORY FOR kNN)
# ------------------------------------------------------------
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

# ------------------------------------------------------------
# 8. TRAIN kNN MODEL
# ------------------------------------------------------------
knn = KNeighborsClassifier(
    n_neighbors=7,
    weights='distance',
    metric='minkowski'
)

knn.fit(X_train_scaled, y_train)

# ------------------------------------------------------------
# 9. PREDICTION
# ------------------------------------------------------------
y_pred = knn.predict(X_test_scaled)

# ------------------------------------------------------------
# 10. EVALUATION METRICS
# ------------------------------------------------------------
accuracy  = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall    = recall_score(y_test, y_pred)
f1        = f1_score(y_test, y_pred)

print("\n===== kNN PERFORMANCE =====")
print(f"Accuracy  : {accuracy*100:.2f}%")
print(f"Precision : {precision*100:.2f}%")
print(f"Recall    : {recall*100:.2f}%")
print(f"F1 Score  : {f1*100:.2f}%")

# ------------------------------------------------------------
# 11. CONFUSION MATRIX
# ------------------------------------------------------------
cm = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:")
print(cm)

ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=["I/O-bound", "CPU-bound"]
).plot()

plt.title("Confusion Matrix – kNN (CPU vs I/O)")
plt.show()

print("\n✅ FINAL kNN EXECUTION SUCCESSFUL")

# ============================================================
# FINAL IMPROVED LOGISTIC REGRESSION – SMARTSCHEDULER
# CPU-bound vs I/O-bound (bpftrace CSV)
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    ConfusionMatrixDisplay
)

# ------------------------------------------------------------
# 1. LOAD CSV (bpftrace files have NO header)
# ------------------------------------------------------------
df = pd.read_csv(
    '/content/sched_3F_20_sec.csv',
    header=None,
    names=['event', 'timestamp', 'pid', 'comm', 'cpu', 'value']
)

print("Dataset loaded")
print(df.head())

# ------------------------------------------------------------
# 2. DATA CLEANING
# ------------------------------------------------------------
df['event'] = df['event'].astype(str)

df['event_type'] = df['event'].map({
    'sched_runtime': 0,
    'sched_switch': 1,
    'sched_wakeup': 2
}).fillna(0)

for col in ['timestamp', 'pid', 'cpu', 'value']:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df.fillna(0, inplace=True)

# ------------------------------------------------------------
# 3. FEATURE ENGINEERING (NO LABEL LEAKAGE)
# ------------------------------------------------------------
features = pd.DataFrame()

features['pid'] = df['pid']
features['cpu'] = df['cpu']

features['runtime_ns'] = np.where(
    df['event_type'] == 0,
    df['value'],
    0
)

features['switch_count'] = np.where(
    df['event_type'] == 1,
    1,
    0
)

features['wakeup_count'] = np.where(
    df['event_type'] == 2,
    1,
    0
)

# ------------------------------------------------------------
# 4. AGGREGATE PER PID
# ------------------------------------------------------------
sched_df = features.groupby('pid', as_index=False).agg({
    'cpu': 'mean',
    'runtime_ns': 'sum',
    'switch_count': 'sum',
    'wakeup_count': 'sum'
})

print("\nAggregated features:")
print(sched_df.head())

# ------------------------------------------------------------
# 5. LABEL CREATION (CPU vs I/O) – SAFE
# ------------------------------------------------------------
runtime_thr = sched_df['runtime_ns'].median()
wakeup_thr  = sched_df['wakeup_count'].median()

sched_df['label'] = np.where(
    (sched_df['runtime_ns'] > runtime_thr) &
    (sched_df['wakeup_count'] <= wakeup_thr),
    1,   # CPU-bound
    0    # I/O-bound
)

print("\nLabel distribution (0=IO, 1=CPU):")
print(sched_df['label'].value_counts())

# ------------------------------------------------------------
# 6. TRAIN–TEST SPLIT
# ------------------------------------------------------------
X = sched_df[
    ['cpu', 'runtime_ns', 'switch_count', 'wakeup_count']
]
y = sched_df['label']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42,
    stratify=y
)

# ------------------------------------------------------------
# 7. FEATURE SCALING (MANDATORY)
# ------------------------------------------------------------
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

# ------------------------------------------------------------
# 8. TRAIN LOGISTIC REGRESSION (IMPROVED)
# ------------------------------------------------------------
logreg = LogisticRegression(
    max_iter=2000,
    solver='lbfgs',
    class_weight='balanced'   # KEY FIX
)

logreg.fit(X_train_scaled, y_train)

# ------------------------------------------------------------
# 9. PROBABILITY + THRESHOLD TUNING
# ------------------------------------------------------------
y_prob = logreg.predict_proba(X_test_scaled)[:, 1]

# Scheduler-aware threshold
threshold = 0.35
y_pred = (y_prob >= threshold).astype(int)

# ------------------------------------------------------------
# 10. EVALUATION METRICS
# ------------------------------------------------------------
accuracy  = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, zero_division=0)
recall    = recall_score(y_test, y_pred, zero_division=0)
f1        = f1_score(y_test, y_pred, zero_division=0)

print("\n===== LOGISTIC REGRESSION RESULTS =====")
print(f"Accuracy  : {accuracy*100:.2f}%")
print(f"Precision : {precision*100:.2f}%")
print(f"Recall    : {recall*100:.2f}%")
print(f"F1 Score  : {f1*100:.2f}%")

# ------------------------------------------------------------
# 11. CONFUSION MATRIX
# ------------------------------------------------------------
cm = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:")
print(cm)

ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=["I/O-bound", "CPU-bound"]
).plot()

plt.title("Confusion Matrix – Logistic Regression (Improved)")
plt.show()

print("\n✅ FINAL LOGISTIC REGRESSION EXECUTION SUCCESSFUL")